from __future__ import annotations

"""RED-first renderer-response calibration contract from real WO-053 evidence.

The ten observations below are frozen from Owner-operated Lightroom job
job-1789004603:
- baseline measurement: measurement-results.json
- actual Exposure2012 delta requested/applied: exposure-plan.json + apply evidence
- fresh-render measurement after that known delta: verification-results.json

This is an acceptance dataset, not values generated by the candidate estimator.
Each test hides one image, fits only on the other nine observations, and requires
the estimator to recover the hidden Lightroom Exposure2012 delta within one
0.05 EV quantum. Do not change expected EV values to make an implementation pass.
"""

import math

import pytest

import lr_ai_exposure.hybrid_exposure as hybrid


# (filename, baseline_measurement, fresh_measurement_after_known_apply, actual_applied_ev)
LIVE_RESPONSE_CASES = (
    ("PTO_3868", 0.5994784235954285, 0.6784195899963379, +0.35),
    ("PTO_3869", 0.6082506179809570, 0.6757431626319885, +0.30),
    ("PTO_3871", 0.6970835626125336, 0.7156122028827667, +0.10),
    ("PTO_3872", 0.6490084528923035, 0.6909455060958862, +0.20),
    ("PTO_3883", 0.5435690283775330, 0.49524158239364624, -0.20),
    ("PTO_3888", 0.5512416362762451, 0.4736078679561615, -0.30),
    ("PTO_3889", 0.5182951092720032, 0.4559866786003113, -0.25),
    ("PTO_3891", 0.6879870593547821, 0.7183455228805542, +0.15),
    ("PTO_3894", 0.7549521923065186, 0.7363607883453369, -0.10),
    ("PTO_3914", 0.8322980403900146, 0.7935922145843506, -0.25),
)


def _estimator():
    candidate = getattr(hybrid, "estimate_renderer_calibrated_delta_ev", None)
    assert callable(candidate), (
        "Missing renderer-calibrated Exposure estimator. Production must not treat "
        "display-JPEG log2 brightness ratio as Lightroom Exposure2012 EV."
    )
    return candidate


@pytest.mark.parametrize(
    "hidden_index",
    range(len(LIVE_RESPONSE_CASES)),
    ids=[case[0] for case in LIVE_RESPONSE_CASES],
)
def test_leave_one_out_recovers_known_lightroom_ev(hidden_index: int) -> None:
    """Nine real response pairs must predict the hidden tenth within one EV quantum."""
    estimate = _estimator()
    filename, baseline, fresh, expected_ev = LIVE_RESPONSE_CASES[hidden_index]
    calibration_samples = [
        (b, f, ev)
        for index, (_, b, f, ev) in enumerate(LIVE_RESPONSE_CASES)
        if index != hidden_index
    ]

    predicted = estimate(
        calibration_samples=calibration_samples,
        baseline_measurement=baseline,
        target_measurement=fresh,
        quantum_ev=0.05,
        max_abs_ev=3.0,
    )

    assert math.isfinite(predicted), f"{filename}: estimator returned non-finite EV"
    assert abs(float(predicted) - expected_ev) <= 0.05 + 1e-12, (
        f"{filename}: expected Lightroom EV {expected_ev:+.2f}, "
        f"predicted {float(predicted):+.3f}; error exceeds one 0.05 EV quantum"
    )


def test_calibration_rejects_zero_delta_response_sample() -> None:
    estimate = _estimator()
    with pytest.raises((ValueError, hybrid.RendererResponseUncertain)):
        estimate(
            calibration_samples=[(0.50, 0.55, 0.0)],
            baseline_measurement=0.50,
            target_measurement=0.55,
            quantum_ev=0.05,
            max_abs_ev=3.0,
        )


def test_calibration_rejects_non_monotonic_response_sample() -> None:
    estimate = _estimator()
    # Positive Exposure2012 must not be calibrated from a measurement that moved darker.
    with pytest.raises((ValueError, hybrid.RendererResponseUncertain)):
        estimate(
            calibration_samples=[(0.60, 0.55, +0.20), (0.50, 0.55, +0.20)],
            baseline_measurement=0.55,
            target_measurement=0.60,
            quantum_ev=0.05,
            max_abs_ev=3.0,
        )
